backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
    - name: "general"
      label: "Site Settings"
      file: "site/data/settings.yaml"
      description: "General Site Settings"
      fields:
        - label: "Site Settings"
          name: site-settings
          widget: "object"
          fields:
          - {label: "Site title", name: "site-title", widget: "string"}
          - {label: "Copy right", name: "copy-right", widget: "string"}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Address", name: "address", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Linkedin", name: "linkedin", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Google", name: "google", widget: "string", required: false}

        
        - label: "Author Settings"
          name: author-settings
          widget: "object"
          fields:
          - {label: "No avatar", name: "no-avatar", widget: "image", class: "thumb"}

        - label: "Post Settings"
          name: post-settings
          widget: "object"
          fields:
            - {label: "Number of posts on frontpage", name: front-limit, widget: number}
            - {label: "Default Author", name: author, widget: relation, collection: authors, searchFields: [title], valueField: title}

  - name: "authors"
    label: "Authors"
    folder: "site/content/authors"
    create: true
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Avatar", name: "image", widget: "image", class: "thumb"}
    - {label: "Description", name: "description", widget: "markdown"}
    - {label: "Twitter", name: "twitter", widget: "string", required: false}
    - {label: "Facebook", name: "facebook", widget: "string", required: false}
    - {label: "Linkedin", name: "linkedin", widget: "string", required: false}
    - {label: "Instagram", name: "instagram", widget: "string", required: false}
    - {label: "Google", name: "google", widget: "string", required: false}

  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:

      - file: "site/content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Topmenu, name: topmenu, widget: hidden, default: "true"}
          - {label: Meta Title, name: meta-title, widget: string}
          - {label: Meta Keywords, name: keywords, widget: string}
          - {label: Meta Description, name: meta-description, widget: text}
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: page}
          - {label: Page, name: page, widget: hidden, default: "/index.html"}
          - {label: Heading, name: h1, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Slider
            name: slider
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Image, name: image, widget: image}
          
          - label: Sections
            name: sections
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Image, name: image, widget: image, required: false}
            - {label: Intro, name: intro, widget: markdown}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
            - {label: Name, name: name, widget: string}
            - {label: Avatar, name: avatar, widget: image, required: false}
            - {label: Testimonial, name: testimonial, widget: text}

      - file: "site/content/careers.md"
        label: "Careers"
        name: "careers"
        fields:
          - {label: Topmenu, name: topmenu, widget: hidden, default: true}
          - {label: Meta Title, name: meta-title, widget: string}
          - {label: Meta Keywords, name: keywords, widget: string}
          - {label: Meta Description, name: meta-description, widget: text}
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: page}
          - {label: Page, name: page, widget: hidden, default: "/careers.html"}


      - file: "site/content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: Topmenu, name: topmenu, widget: hidden, default: true}
          - {label: Meta Title, name: meta-title, widget: string}
          - {label: Meta Keywords, name: keywords, widget: string}
          - {label: Meta Description, name: meta-description, widget: text}
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: page}
          - {label: Page, name: page, widget: hidden, default: "/contact.html"}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Heading, name: heading, widget: string, required: false}
          - {label: Description, name: description, widget: string, required: false}
          - label: Intr
            name: intro
            widget: object
            required: false
            fields: 
            - {label: Heading, name: heading, widget: string}
            - {label: Description, name: description, widget: text}
            - {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}
          - {label: Main, name: main, widget: object, required: false, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}



      - file: "site/content/products.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Topmenu, name: topmenu, widget: hidden, default: true}
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: page}
          - {label: Page, name: page, widget: hidden, default: "/products.html"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
